logging:
    config: classpath:logback.xml
server:
    port: 8081
xxl:
    job:
        accessToken: default_token
        admin:
            addresses: http://localhost:8080/xxl-job-admin     # 调度中心地址
        executor:   # 执行器
            address: ''
            appname: xxl-job-executor-sample    # 执行器名称
            ip: ''
            logpath: /data/applogs/xxl-job/jobhandler
            logretentiondays: 30
            port: 9999
