spring:
    kafka:
        bootstrap-servers: 175.178.87.185:9092  # Kafka集群
        consumer:   # 消费者
            auto:
                commit:
                    interval:
                        ms: 1000    # 提交offset延时(接收到消息后多久提交offset)
            auto-offset-reset: latest   #
            enable-auto-commit: true    # 自动提交offset
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            properties:
                group:
                    id: defaultConsumerGroup     # 默认的消费组ID
                request:
                    timeout:
                        ms: 180000
                session:
                    timeout:
                        ms: 120000
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        listener:
            missing-topics-fatal: false
        producer:   # 生产者配置
            acks: 1 # 应答级别:多少个分区副本备份完成时向生产者发送ack确认(可选0、1、all/-1)
            buffer-memory: 33554432
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
            # 当生产端积累的消息达到batch-size或接收到消息linger.ms后,生产者就会将消息提交给kafka
            # linger.ms为0表示每接收到一条消息就提交给kafka,这时候batch-size其实就没用了
            batch-size: 16384   # 批量大小
            properties:
                linger:
                    ms: 0
            retries: 0  # 重试次数

